### ISSUE TITLE
Set global delay for all test robots

### ISSUE THREAD

**Issue by Husterknupp** [FRosner/DataGenerator#104] opened 2013-09-16 08:30 UTC
On slow machines the GUI tests may fail due to a too fast clicking robot. When setting the robot delay globally it is easy to adjust it when tests fail.

Maybe we can adjust the delay dynamically depending on the available performance (e.g. #CPUs).

**Comment by FRosner** [comment] 2013-09-17 19:54
Fixed by removing robots completely. See #105.

**Comment by Husterknupp** [comment] 2013-09-18 08:19
Robot delay still exists in TestTabbing

**Comment by FRosner** [comment] 2013-09-18 15:16
See #107

**Comment by Bantolomeus** [comment] 2013-09-18 15:40
I used `git pull` the last time. Now I used `git pull` too. `mvn clean` and `mvn package` afterwards. I can see the difference in the test speed. I do not think the error is because of the computer speed (but I have no idea).
![error2](https://f.cloud.github.com/assets/1318613/1166274/a71447ca-2078-11e3-9ea9-48933f2a3a71.JPG)

**Comment by FRosner** [comment] 2013-09-18 15:43
Should be fixed now.

**Comment by Bantolomeus** [comment] 2013-09-18 15:44
Well I do not know why, but after I closed dropbox, skype and firefox the build was a success.
@FRosner I did not pulled the project and it worked.

**Closed as completed by FRosner** 2013-09-18 15:43 UTC
Labels: test

**Comment by FRosner** [comment] 2013-09-18 15:46
The problem is because of the speed. Our robot is trying to do GUI actions (pressing buttons etc.) and so on. If your PC is slow the robot takes too much time and the test thinks the action did not happen. That is why the delay has to be long enough even for slow computers.

However, some tests may fail if you move your mouse or use your keyboard during the test. Avoid using your PC during GUI tests.

**Comment by Bantolomeus** [comment] 2013-09-18 15:47
Alright. It works after your last chance, too.

Alright. It works after your last change, too.
